name: FullPvP
main: net.panda.fullpvp.FullPvP
version: 1.0.0
author: [TulioTriste, Risas]
commands:
   fly:
   heal:
   repairall:
     aliases: [fixall]
   repair:
     aliases: [fix]
   fullpvp:
   warp:
   refund:
   top:
   reply:
     aliases: [r]
   message:
     aliases: [m, msg]
   enderchest:
     aliases: [ec]
   gamemode:
     aliases: [gm]
   invsee:
   kit:
   enchant:
   feed:
   points:
     aliases: [dp, dragonpoints]
   tournament:
     aliases: [tour]
   host:
     aliases: [event]
   staffmode:
     aliases: [mod, staff, modmode, h]
   vanish:
     aliases: [v]
   freeze:
     aliases: [ss]
   chatclear:
     aliases: [cc]
   broadcast:
     aliases: [bc]
   craft:
   rename:
   points:
   discord:
   more:
   store:
   teamspeak:
     aliases: [ts]
   twitter:
   website:
   list:
      aliases: [players]
   setspawn:
      description: Set the default spawn at player location
   spawn:
      description: Teleport to the Spawn
   economy:
      description: Manage the balance of another player
      aliases: [eco, bal, balance, money]
   pay:
      description: Pay to player
      aliases: [p2p]
   stats:
      description: Check the stats of a player
      aliases: [statistic]
   statsmanager:
      description: Edit kills or deaths of a player
      aliases: [statsedit, statsman]
   claim:
      description: null
      aliases: [claimset, claimcreate, createclaim]
   headloot:
      description: Give a HeadLoot, to receive a good loot
      aliases: [hl]
   kit:
      description: Kits
      aliases: [kits]
   dtc:
      description: Destroy The Core Event
      aliases: [destroythecore]
   clan: 